#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef UNIFFI_CPP_INTERNALSTRUCTS
#define UNIFFI_CPP_INTERNALSTRUCTS
struct ForeignBytes {
    int32_t len;
    uint8_t *data;
};

struct RustBuffer {
    uint64_t capacity;
    uint64_t len;
    uint8_t *data;
};

struct RustCallStatus {
    int8_t code;
    RustBuffer error_buf;
};

#endif
struct UniffiVTableCallbackInterfaceCallback {
    void * on_order;
    void * on_order_changed;
    void * on_filled;
    void * on_futopt_order;
    void * on_futopt_order_changed;
    void * on_futopt_filled;
    void * on_event;
    void * uniffi_free;
};
void * uniffi_fubon_fn_clone_accounting(void * ptr, RustCallStatus *out_status);
void uniffi_fubon_fn_free_accounting(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_accounting_bank_remain(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_accounting_inventories(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_accounting_maintenance(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_accounting_query_settlement(void * ptr, RustBuffer account, RustBuffer range, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_accounting_realized_gains_and_loses(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_accounting_realized_gains_and_loses_summary(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_accounting_unrealized_gains_and_loses(void * ptr, RustBuffer account, RustCallStatus *out_status);
void * uniffi_fubon_fn_clone_fuboncore(void * ptr, RustCallStatus *out_status);
void uniffi_fubon_fn_free_fuboncore(void * ptr, RustCallStatus *out_status);
void * uniffi_fubon_fn_constructor_fuboncore_new(RustBuffer pong_inteval, RustBuffer missed_count, RustBuffer url, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuboncore_apikey_dma_login(void * ptr, RustBuffer personal_id, RustBuffer api_key, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuboncore_apikey_login(void * ptr, RustBuffer personal_id, RustBuffer api_key, RustBuffer cert_path, RustBuffer cert_pass, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuboncore_dma_login(void * ptr, RustBuffer personal_id, RustBuffer password, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuboncore_exchange_realtime_token(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuboncore_get_ref(void * ptr, RustCallStatus *out_status);
void uniffi_fubon_fn_method_fuboncore_inner_register_callback(void * ptr, uint64_t callback, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuboncore_login(void * ptr, RustBuffer personal_id, RustBuffer password, RustBuffer cert_path, RustBuffer cert_pass, RustCallStatus *out_status);
int8_t uniffi_fubon_fn_method_fuboncore_logout(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuboncore_recover_event_data(void * ptr, RustCallStatus *out_status);
void * uniffi_fubon_fn_clone_fuglerealtime(void * ptr, RustCallStatus *out_status);
void uniffi_fubon_fn_free_fuglerealtime(void * ptr, RustCallStatus *out_status);
void * uniffi_fubon_fn_constructor_fuglerealtime_new(RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuglerealtime_fubon_ws_url(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuglerealtime_realtime_rest_url(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuglerealtime_realtime_ws_normal_url(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_fuglerealtime_realtime_ws_speed_url(void * ptr, RustCallStatus *out_status);
void * uniffi_fubon_fn_clone_futoptaccounting(void * ptr, RustCallStatus *out_status);
void uniffi_fubon_fn_free_futoptaccounting(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptaccounting_close_position_record(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptaccounting_query_hybrid_position(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptaccounting_query_margin_equity(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptaccounting_query_single_position(void * ptr, RustBuffer account, RustCallStatus *out_status);
void * uniffi_fubon_fn_clone_futoptfunctions(void * ptr, RustCallStatus *out_status);
void uniffi_fubon_fn_free_futoptfunctions(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_batch_cancel_order(void * ptr, RustBuffer account, RustBuffer orders, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_batch_modify_lot(void * ptr, RustBuffer account, RustBuffer orders, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_batch_modify_price(void * ptr, RustBuffer account, RustBuffer orders, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_batch_order_detail(void * ptr, RustBuffer account, RustBuffer batch, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_batch_order_lists(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_batch_place_order(void * ptr, RustBuffer account, RustBuffer orders, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_cancel_condition_orders(void * ptr, RustBuffer account, RustBuffer guid, RustBuffer market_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_cancel_order(void * ptr, RustBuffer account, RustBuffer order_res, RustBuffer unblock, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_convert_symbol(void * ptr, RustBuffer stock_symbol, RustBuffer expiry_date, RustBuffer strike_price, RustBuffer call_put, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_filled_history(void * ptr, RustBuffer account, RustBuffer market_type, RustBuffer start_date, RustBuffer end_date, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_get_condition_history(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer market_type, RustBuffer history_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_get_condition_order(void * ptr, RustBuffer account, RustBuffer market_type, RustBuffer condition_status, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_get_condition_order_by_id(void * ptr, RustBuffer account, RustBuffer guid, RustBuffer market_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_get_order_results(void * ptr, RustBuffer account, RustBuffer market_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_get_order_results_detail(void * ptr, RustBuffer account, RustBuffer market_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_get_time_slice_order(void * ptr, RustBuffer account, RustBuffer batch_no, RustBuffer market_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_get_trail_history(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer market_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_get_trail_order(void * ptr, RustBuffer account, RustBuffer market_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_make_modify_lot_obj(void * ptr, RustBuffer order, int64_t lot, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_make_modify_price_obj(void * ptr, RustBuffer order, RustBuffer price, RustBuffer price_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_modify_lot(void * ptr, RustBuffer account, RustBuffer modify_obj, RustBuffer unblock, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_modify_price(void * ptr, RustBuffer account, RustBuffer modify_obj, RustBuffer unblock, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_multi_condition(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer stop_sign, RustBuffer conditions, RustBuffer order, RustBuffer child_info, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_order_history(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer market_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_place_order(void * ptr, RustBuffer account, RustBuffer order, RustBuffer unblock, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_query_estimate_margin(void * ptr, RustBuffer account, RustBuffer order, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_single_condition(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer stop_sign, RustBuffer condition, RustBuffer order, RustBuffer child_info, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_time_slice_order(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer stop_sign, RustBuffer split_description, RustBuffer order, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_futoptfunctions_trail_profit(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer stop_sign, RustBuffer trail_order, RustCallStatus *out_status);
void * uniffi_fubon_fn_clone_stockfunctions(void * ptr, RustCallStatus *out_status);
void uniffi_fubon_fn_free_stockfunctions(void * ptr, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_batch_cancel_order(void * ptr, RustBuffer account, RustBuffer orders, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_batch_modify_price(void * ptr, RustBuffer account, RustBuffer orders, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_batch_modify_quantity(void * ptr, RustBuffer account, RustBuffer orders, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_batch_order_detail(void * ptr, RustBuffer account, RustBuffer batch, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_batch_order_lists(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_batch_place_order(void * ptr, RustBuffer account, RustBuffer orders, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_cancel_condition_orders(void * ptr, RustBuffer account, RustBuffer guid, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_cancel_order(void * ptr, RustBuffer account, RustBuffer order_res, RustBuffer unblock, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_daytrade_and_stock_info(void * ptr, RustBuffer account, RustBuffer stock_no, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_filled_history(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_get_condition_daytrade_by_id(void * ptr, RustBuffer account, RustBuffer guid, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_get_condition_history(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer history_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_get_condition_order(void * ptr, RustBuffer account, RustBuffer condition_status, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_get_condition_order_by_id(void * ptr, RustBuffer account, RustBuffer guid, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_get_order_results(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_get_order_results_detail(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_get_time_slice_order(void * ptr, RustBuffer account, RustBuffer batch_no, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_get_trail_history(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_get_trail_order(void * ptr, RustBuffer account, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_make_modify_price_obj(void * ptr, RustBuffer order, RustBuffer price, RustBuffer price_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_make_modify_quantity_obj(void * ptr, RustBuffer order, int64_t quantity, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_margin_quota(void * ptr, RustBuffer account, RustBuffer stock_no, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_modify_price(void * ptr, RustBuffer account, RustBuffer modify_obj, RustBuffer unblock, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_modify_quantity(void * ptr, RustBuffer account, RustBuffer modify_obj, RustBuffer unblock, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_multi_condition(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer stop_sign, RustBuffer conditions, RustBuffer order, RustBuffer child_info, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_multi_condition_day_trade(void * ptr, RustBuffer account, RustBuffer stop_sign, RustBuffer end_time, RustBuffer conditions, RustBuffer order, RustBuffer condition_day_trade, RustBuffer child_info, RustBuffer fix_session, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_multi_condition_stop(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer stop_sign, RustBuffer conditions, RustBuffer order, RustBuffer stop_conditions, RustBuffer second_stop_conditions, RustBuffer child_info, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_order_history(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_place_order(void * ptr, RustBuffer account, RustBuffer order, RustBuffer unblock, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_query_symbol_quote(void * ptr, RustBuffer account, RustBuffer symbol, RustBuffer market_type, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_query_symbol_snapshot(void * ptr, RustBuffer account, RustBuffer market_type, RustBuffer stock_types, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_single_condition(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer stop_sign, RustBuffer condition, RustBuffer order, RustBuffer child_info, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_single_condition_day_trade(void * ptr, RustBuffer account, RustBuffer stop_sign, RustBuffer end_time, RustBuffer condition, RustBuffer order, RustBuffer condition_day_trade, RustBuffer child_info, RustBuffer fix_session, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_single_condition_stop(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer stop_sign, RustBuffer condition, RustBuffer order, RustBuffer stop_conditions, RustBuffer second_stop_conditions, RustBuffer child_info, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_time_slice_order(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer stop_sign, RustBuffer split_description, RustBuffer order, RustCallStatus *out_status);
RustBuffer uniffi_fubon_fn_method_stockfunctions_trail_profit(void * ptr, RustBuffer account, RustBuffer start_date, RustBuffer end_date, RustBuffer stop_sign, RustBuffer trail_order, RustCallStatus *out_status);
void uniffi_fubon_fn_init_callback_vtable_callback(UniffiVTableCallbackInterfaceCallback & vtable);
RustBuffer ffi_fubon_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status);
RustBuffer ffi_fubon_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status);
void ffi_fubon_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status);
RustBuffer ffi_fubon_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status);
uint16_t uniffi_fubon_checksum_method_accounting_bank_remain();
uint16_t uniffi_fubon_checksum_method_accounting_inventories();
uint16_t uniffi_fubon_checksum_method_accounting_maintenance();
uint16_t uniffi_fubon_checksum_method_accounting_query_settlement();
uint16_t uniffi_fubon_checksum_method_accounting_realized_gains_and_loses();
uint16_t uniffi_fubon_checksum_method_accounting_realized_gains_and_loses_summary();
uint16_t uniffi_fubon_checksum_method_accounting_unrealized_gains_and_loses();
uint16_t uniffi_fubon_checksum_method_fuboncore_apikey_dma_login();
uint16_t uniffi_fubon_checksum_method_fuboncore_apikey_login();
uint16_t uniffi_fubon_checksum_method_fuboncore_dma_login();
uint16_t uniffi_fubon_checksum_method_fuboncore_exchange_realtime_token();
uint16_t uniffi_fubon_checksum_method_fuboncore_get_ref();
uint16_t uniffi_fubon_checksum_method_fuboncore_inner_register_callback();
uint16_t uniffi_fubon_checksum_method_fuboncore_login();
uint16_t uniffi_fubon_checksum_method_fuboncore_logout();
uint16_t uniffi_fubon_checksum_method_fuboncore_recover_event_data();
uint16_t uniffi_fubon_checksum_method_fuglerealtime_fubon_ws_url();
uint16_t uniffi_fubon_checksum_method_fuglerealtime_realtime_rest_url();
uint16_t uniffi_fubon_checksum_method_fuglerealtime_realtime_ws_normal_url();
uint16_t uniffi_fubon_checksum_method_fuglerealtime_realtime_ws_speed_url();
uint16_t uniffi_fubon_checksum_method_futoptaccounting_close_position_record();
uint16_t uniffi_fubon_checksum_method_futoptaccounting_query_hybrid_position();
uint16_t uniffi_fubon_checksum_method_futoptaccounting_query_margin_equity();
uint16_t uniffi_fubon_checksum_method_futoptaccounting_query_single_position();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_batch_cancel_order();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_batch_modify_lot();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_batch_modify_price();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_batch_order_detail();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_batch_order_lists();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_batch_place_order();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_cancel_condition_orders();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_cancel_order();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_convert_symbol();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_filled_history();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_get_condition_history();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_get_condition_order();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_get_condition_order_by_id();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_get_order_results();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_get_order_results_detail();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_get_time_slice_order();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_get_trail_history();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_get_trail_order();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_make_modify_lot_obj();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_make_modify_price_obj();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_modify_lot();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_modify_price();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_multi_condition();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_order_history();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_place_order();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_query_estimate_margin();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_single_condition();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_time_slice_order();
uint16_t uniffi_fubon_checksum_method_futoptfunctions_trail_profit();
uint16_t uniffi_fubon_checksum_method_stockfunctions_batch_cancel_order();
uint16_t uniffi_fubon_checksum_method_stockfunctions_batch_modify_price();
uint16_t uniffi_fubon_checksum_method_stockfunctions_batch_modify_quantity();
uint16_t uniffi_fubon_checksum_method_stockfunctions_batch_order_detail();
uint16_t uniffi_fubon_checksum_method_stockfunctions_batch_order_lists();
uint16_t uniffi_fubon_checksum_method_stockfunctions_batch_place_order();
uint16_t uniffi_fubon_checksum_method_stockfunctions_cancel_condition_orders();
uint16_t uniffi_fubon_checksum_method_stockfunctions_cancel_order();
uint16_t uniffi_fubon_checksum_method_stockfunctions_daytrade_and_stock_info();
uint16_t uniffi_fubon_checksum_method_stockfunctions_filled_history();
uint16_t uniffi_fubon_checksum_method_stockfunctions_get_condition_daytrade_by_id();
uint16_t uniffi_fubon_checksum_method_stockfunctions_get_condition_history();
uint16_t uniffi_fubon_checksum_method_stockfunctions_get_condition_order();
uint16_t uniffi_fubon_checksum_method_stockfunctions_get_condition_order_by_id();
uint16_t uniffi_fubon_checksum_method_stockfunctions_get_order_results();
uint16_t uniffi_fubon_checksum_method_stockfunctions_get_order_results_detail();
uint16_t uniffi_fubon_checksum_method_stockfunctions_get_time_slice_order();
uint16_t uniffi_fubon_checksum_method_stockfunctions_get_trail_history();
uint16_t uniffi_fubon_checksum_method_stockfunctions_get_trail_order();
uint16_t uniffi_fubon_checksum_method_stockfunctions_make_modify_price_obj();
uint16_t uniffi_fubon_checksum_method_stockfunctions_make_modify_quantity_obj();
uint16_t uniffi_fubon_checksum_method_stockfunctions_margin_quota();
uint16_t uniffi_fubon_checksum_method_stockfunctions_modify_price();
uint16_t uniffi_fubon_checksum_method_stockfunctions_modify_quantity();
uint16_t uniffi_fubon_checksum_method_stockfunctions_multi_condition();
uint16_t uniffi_fubon_checksum_method_stockfunctions_multi_condition_day_trade();
uint16_t uniffi_fubon_checksum_method_stockfunctions_multi_condition_stop();
uint16_t uniffi_fubon_checksum_method_stockfunctions_order_history();
uint16_t uniffi_fubon_checksum_method_stockfunctions_place_order();
uint16_t uniffi_fubon_checksum_method_stockfunctions_query_symbol_quote();
uint16_t uniffi_fubon_checksum_method_stockfunctions_query_symbol_snapshot();
uint16_t uniffi_fubon_checksum_method_stockfunctions_single_condition();
uint16_t uniffi_fubon_checksum_method_stockfunctions_single_condition_day_trade();
uint16_t uniffi_fubon_checksum_method_stockfunctions_single_condition_stop();
uint16_t uniffi_fubon_checksum_method_stockfunctions_time_slice_order();
uint16_t uniffi_fubon_checksum_method_stockfunctions_trail_profit();
uint16_t uniffi_fubon_checksum_constructor_fuboncore_new();
uint16_t uniffi_fubon_checksum_constructor_fuglerealtime_new();
uint16_t uniffi_fubon_checksum_method_callback_on_order();
uint16_t uniffi_fubon_checksum_method_callback_on_order_changed();
uint16_t uniffi_fubon_checksum_method_callback_on_filled();
uint16_t uniffi_fubon_checksum_method_callback_on_futopt_order();
uint16_t uniffi_fubon_checksum_method_callback_on_futopt_order_changed();
uint16_t uniffi_fubon_checksum_method_callback_on_futopt_filled();
uint16_t uniffi_fubon_checksum_method_callback_on_event();
uint32_t ffi_fubon_uniffi_contract_version();
#ifdef __cplusplus
}
#endif